### ISSUE TITLE
Generating class-specific localization maps with MCT-v2

### ISSUE THREAD

**Issue by yi94code** [xulianuwa/MCTformer#10]
We find that the run.sh only provide script for generating class-specific localization maps with MCT-v1, but according to your paper, using MCT-v2 is better. Could you please provide the script for generating class-specific localization maps with MCT-v2 or give some more details, e.g., the number of layer index to generate the map? Thanks a lot!

**Comment by PlumedSerpent** [comment]
`######### Generating class-specific localization maps ##########
python main.py --model deit_small_MCTformerV2_patch16_224 \
                --data-set VOC12MS \
                --scales 1.0 \
                --img-list Dataset/VOC2012_SEG_AUG/ImageSets/Segmentation(your path) \
                --data-path Dataset/VOC2012_SEG_AUG/(your path)  \
                --output_dir ./MCTformer_results/MCTformer_v2 \
                --resume MCTformerV2.pth \
                --gen_attention_maps \
                --attention-type fused \
                --layer-index 3 \
                --visualize-cls-attn \
                --patch-attn-refine \
                --attention-dir ./MCTformer_results/MCTformer_v1/attn-patchrefine\
                --cam-npy-dir ./MCTformer_results/MCTformer_v1/attn-patchrefine-npy \

######### Evaluating the generated class-specific localization maps ##########
python evaluation.py --list Dataset/VOC2012_SEG_AUG/ImageSets/Segmentation/train_aug.txt \
                     --gt_dir Dataset/VOC2012_SEG_AUG/SegmentationClassAug \
                     --logfile ./MCTformer_results/MCTformer_v1/attn-patchrefine-npy/evallog.txt \
                     --type npy \
                     --curve True \
                     --predict_dir ./MCTformer_results/MCTformer_v1/attn-patchrefine-npy \
                     --comment "train1464"`

**Comment by yi94code** [comment]
Thanks a lot!

**Comment by yi94code** [comment]
Hi, I have generated the class-specific localization maps according to your script. However, my results are much lower than yours. Is your results calculated on 10582 images or 1464 images (PASCAL VOC train set)? That is, is the "SegmentationClassAug" containing 10582 images? If yes, could you please kindly provided that how to download these ground truth? Thanks!
<img width="610" alt="image" src="https://user-images.githubusercontent.com/44866860/179171774-bd2f0691-fd04-4a40-a7f4-1fa3b7da1cf9.png">

**Comment by PlumedSerpent** [comment]
I'm not the author.
Please make sure you've passed some arguments correctly.
--model deit_small_MCTformerV2_patch16_224 
--resume MCTformerV2.pth
and --cam-npy-dir should be the same as the --predict_dir in the evaluation step.

**Comment by PlumedSerpent** [comment]
BTW, the other GroundTruth masks can be download from:
http://home.bharathh.info/pubs/codes/SBD/download.html

**Comment by yi94code** [comment]
> I'm not the author. Please make sure you've passed some arguments correctly. --model deit_small_MCTformerV2_patch16_224 --resume MCTformerV2.pth and --cam-npy-dir should be the same as the --predict_dir in the evaluation step.

Thanks for your kind help! By using the weight that the author provided, mIoU can reach 61.685%. However, when I use scripts that the author provided to train MCTformerV2, the generated class-specific localization maps are much poor and the best mIoU is 54.945%. Have you ever encountered this problem?

**Comment by Gptao** [comment]
######### train MCTformer V2 ##########
python main.py --model deit_small_MCTformerV2_patch16_224 \
                --batch-size 64 \
                --data-set VOC12 \
                --img-list voc12 \
                --data-path ./Datasets/VOCdevkit/VOC2012 \
                --layer-index 12 \
                --output_dir ./MCTformer_results/MCTformer_v2 \
                --finetune https://dl.fbaipublicfiles.com/deit/deit_small_patch16_224-cd65a155.pth

######### Generating class-specific localization maps ##########
python main.py --model deit_small_MCTformerV2_patch16_224 \
                --data-set VOC12MS \
                --scales 1.0 \
                --img-list ./Datasets/VOCdevkit/VOC2012/ImageSets/Segmentation \
                --data-path ./Datasets/VOCdevkit/VOC2012 \
                --output_dir ./MCTformer_results/MCTformer_v2 \
                --resume ./MCTformer_results/MCTformer_v2/checkpoint.pth \
                --gen_attention_maps \
                --attention-type fused \
                --layer-index 3 \
                --visualize-cls-attn \
                --patch-attn-refine \
                --attention-dir ./MCTformer_results/MCTformer_v2/attn-patchrefine \
                --cam-npy-dir ./MCTformer_results/MCTformer_v2/attn-patchrefine-npy \
And "train_aug" in [dataset.py  ](https://github.com/xulianuwa/MCTformer/blob/4267e423a5ea25e0ea399b1f6cd6a68d4958f3f1/datasets.py#L127) should be "train" , I get best mIoU:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/32570671/179797841-cba1f3cb-278b-4bac-949e-e1866f70ce28.png">
still lower than the performance 61.685% mentioned in the paper.  I guess there are data augmentation in training for training dataset is VOC12 not VOC12MS.

**Comment by yi94code** [comment]
> download

Thanks a lot !

**Comment by fwu11** [comment]
I am wondering if anyone sucessfully reproduce the results claimed in the paper now? MCTformer-V2 (Attention + PatchCAM + PatchAffinity) 61.7. After running "Evaluating the generated class-specific localization maps" script with trained MCTformer-V2 on _voc train_ dataset, I was only able to get lower 50s mIOU like the screenshot in the previous comment.

**Comment by zbb1111** [comment]
When I was running, the following error occurred. Where is your model and how does it run?

File "/home/zyp/anaconda3/envs/mct/lib/python3.8/site packages/tim/models/factory. py", line 78, in createModel
Raise RuntimeError ('Unknown model (% s) '% modelname)
RuntimeError: Unknown model (deitsmall MCTFormerV1_patch16_224)
