### ISSUE TITLE
run_seg.sh command line parameters

### ISSUE THREAD

**Issue by AmeenAli** [xulianuwa/MCTformer#11]
Hello,

I am trying to run the run_seg.sh script, and apparently there are a few missing hyperparameters :

can you elaborate more on these missing : 
1.seg_pgt_path
2. img_path

Thanks!

**Comment by Gptao** [comment]
seg_pgt_path is generated pseudo mask path like /MCTformer_results/MCTformer_v2/attn-patchrefine, img_path is /Datasets/VOCdevkit/VOC2012/JPEGImages

**Comment by Gptao** [comment]
What is "init_weights" in command parameters to train the segmentation model?

**Comment by xulianuwa** [comment]
> seg_pgt_path is generated pseudo mask path like /MCTformer_results/MCTformer_v2/attn-patchrefine, img_path is /Datasets/VOCdevkit/VOC2012/JPEGImages

Thanks for that.
