### ISSUE TITLE
some problem about loading pretrained model

### ISSUE THREAD

**Issue by zaiquanyang** [xulianuwa/MCTformer#12]
for the v1, the shape of class-token is class_num x dim, which is inconsistent with the pretrained model 1x dim. Then it appears error when loading the pretrained checkpoint.

**Comment by xulianuwa** [comment]
Did you meet this problem by running this part? https://github.com/xulianuwa/MCTformer/blob/0d4f16471905ef54fe585b070735233f22aa1b05/run.sh#L2-L9

**Comment by zaiquanyang** [comment]
> Did you meet this problem by running this part?
> 
> https://github.com/xulianuwa/MCTformer/blob/0d4f16471905ef54fe585b070735233f22aa1b05/run.sh#L2-L9

yes. I remember I barely changed the code ....
