### ISSUE TITLE
About the pretrained model for segmentation stage.

### ISSUE THREAD

**Issue by xinyuaning** [xulianuwa/MCTformer#14]
Thanks for the great job!
I have some problem about the segmentation stage. The model is pretrained on ImageNet?

**Comment by xulianuwa** [comment]
The segmentation model on VOC was initialized with the weights (https://drive.google.com/file/d/1xESB7017zlZHqxEWuh1Rb89UhjTGIKOA/view) of the pre-trained classification model (ResNet38) on VOC.
