### ISSUE TITLE
How to train COCO?

### ISSUE THREAD

**Issue by zhaoxiaodong789** [xulianuwa/MCTformer#15]
Could you please show me the setting about coco dataset?

**Comment by godlin-bd** [comment]
I have the same question, Does the setting of VOC and COCO datasets any different? Like lr, crop size, epoch_num and so on.

**Comment by zaiquanyang** [comment]
I have the same question, Does the setting of VOC and COCO datasets any different?

**Comment by zhaoxiaodong789** [comment]
收到

**Comment by xulianuwa** [comment]
> Could you please show me the setting about coco dataset?



> I have the same question, Does the setting of VOC and COCO datasets any different? Like lr, crop size, epoch_num and so on.



> I have the same question, Does the setting of VOC and COCO datasets any different?



> Does the problem solved? Where can we find the script for training coco dataset?

The setting for training MCTformer on COCO is same as that on VOC, except using different dataset functions as below.
https://github.com/xulianuwa/MCTformer/blob/bd1e80472446e0e2a4a323555579423ce2ea6562/datasets.py#L34-L101

I will upload a script for COCO next week.

**Comment by Italy2006** [comment]
> > Could you please show me the setting about coco dataset?
> 
> > I have the same question, Does the setting of VOC and COCO datasets any different? Like lr, crop size, epoch_num and so on.
> 
> > I have the same question, Does the setting of VOC and COCO datasets any different?
> 
> > Does the problem solved? Where can we find the script for training coco dataset?
> 
> The setting for training MCTformer on COCO is same as that on VOC, except using different dataset functions as below.
> 
> https://github.com/xulianuwa/MCTformer/blob/bd1e80472446e0e2a4a323555579423ce2ea6562/datasets.py#L34-L101
> 
> I will upload a script for COCO next week.

what about the seg step on COCO?
