### ISSUE TITLE
The result on VOC(val) Resnet38 cannot achieve 71.9

### ISSUE THREAD

**Issue by GuLicheng** [xulianuwa/MCTformer#17]
Hi, I have tried to train resnet38 with pseudo label created by run_psa.sh, but only got 70.4 mIoU on voc val. Can you provide the checkpoint of resnet38_aff.pth?

**Comment by xulianuwa** [comment]
> Hi, I have tried to train resnet38 with pseudo label created by run_psa.sh, but only got 70.4 mIoU on voc val. Can you provide the checkpoint of resnet38_aff.pth?

Hi, here is the link
https://drive.google.com/file/d/1hEGNbPuN_gMOX500TKfnNFHZ4Cscxq51/view?usp=sharing

**Comment by pipizhum** [comment]
> 

Can you provide instructions for all the training steps? I followed the author's instructions and the final segmentation result of mIoU was only 67.5%.
