### ISSUE TITLE
The results of seed cam can't achieve 61 mIoU

### ISSUE THREAD

**Issue by sennnnn** [xulianuwa/MCTformer#18]
I train a MCTFormer-V2 but it can only achieve 55 mIoU. Are the hyperparameters modified after paper is accepted?

**Comment by xulianuwa** [comment]
> I train a MCTFormer-V2 but it can only achieve 55 mIoU. Are the hyperparameters modified after paper is accepted?

Can you set random seed as below and re-run it. 
https://github.com/xulianuwa/MCTformer/blob/bd1e80472446e0e2a4a323555579423ce2ea6562/main.py#L153-L154
