### ISSUE TITLE
Informative: error triggered by package gimm

### ISSUE THREAD

**Issue by fish98** [xulianuwa/MCTformer#19]
Found this error when reproducing the experiment result. 

```bash
/home/visitor/.conda/envs/cv/lib/python3.6/site-packages/torchvision/transforms/transforms.py:288: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Creating model: deit_small_MCTformerV1_patch16_224
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main(args)
  File "main.py", line 194, in main
    drop_block_rate=None
  File "/home/visitor/.conda/envs/cv/lib/python3.6/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/home/visitor/MCTformer/models.py", line 210, in deit_small_MCTformerV1_patch16_224
    norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
  File "/home/visitor/MCTformer/models.py", line 113, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'
```

Ps. this error is fixed after ungrading package gimm from the newest version to 0.5.4.

**Comment by xulianuwa** [comment]
> Found this error when reproducing the experiment result.
> 
> ```shell
> /home/visitor/.conda/envs/cv/lib/python3.6/site-packages/torchvision/transforms/transforms.py:288: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
>   "Argument interpolation should be of type InterpolationMode instead of int. "
> Creating model: deit_small_MCTformerV1_patch16_224
> Traceback (most recent call last):
>   File "main.py", line 320, in <module>
>     main(args)
>   File "main.py", line 194, in main
>     drop_block_rate=None
>   File "/home/visitor/.conda/envs/cv/lib/python3.6/site-packages/timm/models/factory.py", line 71, in create_model
>     model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
>   File "/home/visitor/MCTformer/models.py", line 210, in deit_small_MCTformerV1_patch16_224
>     norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
>   File "/home/visitor/MCTformer/models.py", line 113, in __init__
>     super().__init__(*args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'
> ```
> 
> Ps. this error is fixed after ungrading package gimm from the newest version to 0.5.4.

Thanks for the update.
