### ISSUE TITLE
About the optimizer details

### ISSUE THREAD

**Issue by PlumedSerpent** [xulianuwa/MCTformer#2]
Hi,I am working on implementing this excellent work, and I found the validation loss will decrease in the beginning epochs and increasing for the remaining epochs. The baseline seed miou reaches 43.1 (vs official 47.3). I think the optimizer setting may be the key reason. Here is my optimizer setting( which is the same as the deit official repository:
1.AdamW for the whole network, batchsize=64, epoch = 60.
2.initial lr=5e-4, weight_decay =0.05 (except cls_token and pos_emb)
3. cosine lr scheduler, lr-noise-pct =0.67, lr-noise-std=1.0, min_lr =1e-5
4. warm_up epoch = 5, warmup lr = 1e-6  ( Or no warmup at all)
Did I use some different optimizer with your implementation?

**Comment by xulianuwa** [comment]
Your optimizer setting looks no problem. Btw, I try my best to upload the code soon, thanks for your interests.

**Comment by Unrealluver** [comment]
Hi, bro, I wonder if you have reimplement this author's work? I also meet the low mIoU problem.

**Comment by yi94code** [comment]
> Hi, bro, I wonder if you have reimplement this author's work? I also meet the low mIoU problem.

Hi, did you succee to reimplement this work? I also meet the low mIoU problem.

**Comment by xulianuwa** [comment]
> > Hi, bro, I wonder if you have reimplement this author's work? I also meet the low mIoU problem.
> 
> Hi, did you succee to reimplement this work? I also meet the low mIoU problem.

It should be the problem with random seed. I have updated the code as below
https://github.com/xulianuwa/MCTformer/blob/bd1e80472446e0e2a4a323555579423ce2ea6562/main.py#L153-L154
