### ISSUE TITLE
I have a question about engine.py

### ISSUE THREAD

**Issue by yijiangWang0316** [xulianuwa/MCTformer#21]
Hello author. (When I run the Generating class-specific localization maps step) at line 26, I observe that 'samples' is a list type (the value returned by class VOC12DatasetMS in dataset.py) that should hold the image of a batch and its corresponding flipped image tensor. Every time I run this, it reports an error that the 'list' object has no attribute 'to'. I tried putting each tensor in the list into cuda, but then I got an error in models.py (B, nc, w, h = x.shape), i.e., the 'list' object has no attribute 'shape'. I did not change the source code, but only the num_classes in class VisionTransformer in vision_transformer.py to 20 (the source code defaults to 1000, which does not allow me to train the model properly).
Thanks!

**Comment by xulianuwa** [comment]
> Hello author. (When I run the Generating class-specific localization maps step) at line 26, I observe that 'samples' is a list type (the value returned by class VOC12DatasetMS in dataset.py) that should hold the image of a batch and its corresponding flipped image tensor. Every time I run this, it reports an error that the 'list' object has no attribute 'to'. I tried putting each tensor in the list into cuda, but then I got an error in models.py (B, nc, w, h = x.shape), i.e., the 'list' object has no attribute 'shape'. I did not change the source code, but only the num_classes in class VisionTransformer in vision_transformer.py to 20 (the source code defaults to 1000, which does not allow me to train the model properly). Thanks!

Hello Wangyi, for the generating class-specific localization maps step, because the batch size is 1, you can choose the first item in that 'samples' before moving them to cuda as below:
https://github.com/xulianuwa/MCTformer/blob/38150cd7b5af792dc5bea1605eac72af2ed60a9f/engine.py#L133
Does it solve your problem?

**Comment by wangyijiang0316** [comment]
I made the following change at line 26 in engine.py: samples_list[0].to(device, non_blocking=True). And,images = images_list[0].to(device, non_blocking=True) at line 77.
This works, but doesn't the tensor samples_list[1] need to be trained on cuda? I didn't change the code in line 133 of your reply, the 'image' is not a list, it is a tensor.Can you tell me what are the two tensors stored in the list of 'samples'? My understanding is that one is the original image and one is the flipped image, I don't know if that is correct.
Thank you very much for answering my question in your busy schedule!

**Comment by wangyijiang0316** [comment]
Hello author. There is no problem with your source code. It's a problem I ran on pycharm, the action='store_true' parameter in the main.py file I did not add. I'm very sorry for the delay, there are problems. I'll give you feedback in time! I only changed the class VisionTransformer in vision_transformer.py (num_classes=1000 replaced by 20) otherwise, it doesn't train your initial model. I don't know if this change will affect the final result.
Thanks again for your reply!

**Comment by xulianuwa** [comment]
> 



> I made the following change at line 26 in engine.py: samples_list[0].to(device, non_blocking=True). And,images = images_list[0].to(device, non_blocking=True) at line 77. This works, but doesn't the tensor samples_list[1] need to be trained on cuda? I didn't change the code in line 133 of your reply, the 'image' is not a list, it is a tensor.Can you tell me what are the two tensors stored in the list of 'samples'? My understanding is that one is the original image and one is the flipped image, I don't know if that is correct. Thank you very much for answering my question in your busy schedule!

If samples_list is from VOC12DatasetMS(), the length of sample_list is the batch size, so samples_list[1] is the second image in a batch if the batch size >1; It looks you were using VOC12DatasetMS() for training, but I only used it for generating localization maps, where I set batch size = 1, in that case, sample_list[1] is none, the first dimension of sample[0] is 2, indicating the original image and its flipped counterpart. Let me know if this helps.
