### ISSUE TITLE
Evaluation of the generated class-specific activation map results does not reach the level of the ablation experiments in the paper

### ISSUE THREAD

**Issue by yijiangWang0316** [xulianuwa/MCTformer#22]
Hi，I have the following two questions：
1. I evaluated the seed CAMs generated by MCTformer-V1 and MCTformer-V2 respectively, and they correspond to the best mIoU results: 50.74128% (modelV1) and 58.664% (modelV2), which do not reach the level of the ablation experiments in the paper (55.2% and 61.7%).
2. I would like to ask the authors if the refinement has been performed using patch-level affinity in the generated class-specific activation maps (if so, it really does not correspond to the results of the paper, I did not make changes to the source code, and the random seeds are consistent).
Thanks for your help!

**Comment by xulianuwa** [comment]
Please use my updated requirements to set up the environment and use the following way to set the random seed, the variation should be within +/-1%.
https://github.com/xulianuwa/MCTformer/blob/96065977f38ec07cff3dea7295555d5141502c2d/main.py#L149-L157
