### ISSUE TITLE
Performance Concern.

### ISSUE THREAD

**Issue by Gptao** [xulianuwa/MCTformer#23]
I wonder why  the Pseudo Mask mIoU (train1464) obtained on PascalVOC in the paper is 69.1  which is much lower than that in other papers, but the performance of 71.9 can be obtained on the verification set using PSA and deeplabv1?  The pseudo label performance and segmentation results of other methods are as follows:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/32570671/197784915-a6884510-d3ff-49ed-a6c5-984664bee183.png">
It seems the 71.9 result is hard to reproduce (not small gap) even  all seeds set fixed.

**Comment by xulianuwa** [comment]
1.The pseudo mask evaluation was commonly done on the train set, but it is the augmented train set that is used for training the segmentation model. It's recommended to compare the evaluation results on the augmented train set as well. Our pseudo masks can be downloaded [here.](https://drive.google.com/file/d/16p7yL1iQUBw2NRF9-JUFpWqt91WjE61E/view?usp=sharing) 2.mIoU is not an ideal metric, meaning that pseudo masks with a better mIoU do not guarantee a better segmentation mIoU. You may need to check other metrics, like precision, recall, etc, to have a more comprehensive evaluation. 3.It is acceptable for me if you only compare your segmentation results with our reported ones in the same condition of not using post-processing (i.e., multi-scale testing and CRF). [Here](https://drive.google.com/file/d/1X-d1-MW-Ch6o92R5YGc8tjZRkC8puwU2/view?usp=sharing) is our trained segmentation model.

**Comment by Gptao** [comment]
Besides mIoU,  can you provide codes for calculating other evaluation indicators (precision，recall，pixel_acc) for reference? Thank you very much!
