### ISSUE TITLE
Training our own dataset

### ISSUE THREAD

**Issue by xiaona123456** [xulianuwa/MCTformer#24]
I want to train with our own dataset, what does the npy file inside stand for? Thanks a lot!

**Comment by xulianuwa** [comment]
The numpy file stores the image-level labels (i.e., multi-hot vectors) of the dataset.

**Comment by xiaona123456** [comment]
Thanks you! And I have a another question. 
when training,     
######
for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
        samples = samples.to(device, non_blocking=True)
        targets = targets.to(device, non_blocking=True)
######
the samples's type is list, inside is everal four-dimensional arrays of tensor type,  there triggers a problem: 'list' object has no attribute 'to'.
Can you tell me how to deal with it?
