### ISSUE TITLE
how to make our own cls_label.npy

### ISSUE THREAD

**Issue by mengweibao** [xulianuwa/MCTformer#40]
Dear author, hello, I'm sorry to bother you. How should we make our own cls_label.npy file of the VOC2012 format data set? It would be greatly appreciated if you could reply! @xulianuwa

**Comment by xulianuwa** [comment]
Hi, you can refer to [this](https://github.com/jiwoon-ahn/psa/blob/master/voc12/make_cls_labels.py).
