### ISSUE TITLE
MCTformer+ post-processing parameter problem

### ISSUE THREAD

**Issue by ghost** [xulianuwa/MCTformer#42]
Very interesting work!
Can you give the post-processing parameters of MCTformer+, such as low_alpha and high_alpha? The parameters given in accordance with the MCTformer file cannot meet the miou in the paper on the voc val set.Tks!

**Comment by jungletada** [comment]
Yes, good question.
I also want to know that how the authors post-process on MCTformer+. Since they didn't release the PSA code for generating the pseudo mask. I try the low_alpha and high_alpha given in MCTformer, the results are only 72.6% mIoU.

**Comment by whb919168848** [comment]
> Yes, good question. I also want to know that how the authors post-process on MCTformer+. Since they didn't release the PSA code for generating the pseudo mask. I try the low_alpha and high_alpha given in MCTformer, the results are only 72.6% mIoU.



> Yes, good question. I also want to know that how the authors post-process on MCTformer+. Since they didn't release the PSA code for generating the pseudo mask. I try the low_alpha and high_alpha given in MCTformer, the results are only 72.6% mIoU.

Hello! Have you solved the problem？ I try the low_alpha and high_alpha given in MCTformer, the results are only 69.7% mIoU. Could you please give me your settings ?Thanks.

**Comment by whb919168848** [comment]
@jungletada

**Comment by klxg001** [comment]
Hi, why do I get the following error after running "bash run_mct_plus.sh", aren't these images generated during the run, or do they need to be there before the run? I would be very grateful for your reply!
![22](https://github.com/xulianuwa/MCTformer/assets/145547433/9a85cdac-8f3a-4df1-a352-a91102f2bd80)

**Comment by ghost** [comment]
> Hi, why do I get the following error after running "bash run_mct_plus.sh", aren't these images generated during the run, or do they need to be there before the run? I would be very grateful for your reply!
> ![22](https://github.com/xulianuwa/MCTformer/assets/145547433/9a85cdac-8f3a-4df1-a352-a91102f2bd80)
> 

Have the train MCTformerPlus and Generating class specific localization stages been completed? It seems that this issue is caused by not completing them properly

**Comment by Italy2006** [comment]
> Yes, good question. I also want to know that how the authors post-process on MCTformer+. Since they didn't release the PSA code for generating the pseudo mask. I try the low_alpha and high_alpha given in MCTformer, the results are only 72.6% mIoU.

Have you solved this problem?
